telemetry: remove unused Jeti EX Bus frame counter
./src/main/telemetry/jetiexbus.c: In function 'handleJetiExBusTelemetry':
./src/main/telemetry/jetiexbus.c:558:21: error: variable 'framesLost' set but not used [-Werror=unused-but-set-variable=]
  558 |     static uint16_t framesLost = 0; // only for debug
      |                     ^~~~~~~~~~
cc1: all warnings being treated as errors