Fix ELRS gating issues. (#12055)
* Fix default ELRS timer instance for F405/F745/H7 not taking into account the fact that a target may have set it explicitly.

The compiler error is 'error: "RX_EXPRESSLRS_TIMER_INSTANCE" redefined'.

* The H7RF uses TIM6 and is H7 based.

* ELRS - Fix compilation errors when USE_RX_EXPRESSLRS is defined but when
any of USE_TELEMETRY,USE_TELEMETRY_CRSF,USE_CRSF_LINK_STATISTICS,USE_SERIALRX_CRSF
are not.

ELRS currently depends on CRSF telemetry.